# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    commit-message:
      prefix: 'Updated libs'
    labels:
      - 'libs'
    open-pull-requests-limit: 5

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    commit-message:
      prefix: 'Updated github actions'
    labels:
      - 'libs'
    open-pull-requests-limit: 2
