name: Node Checks

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.10.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: CI command
        run: npm ci

      - name: Linting checks
        run: npm run lint

      - name: Locales tests
        run: npm run test:locales

      - name: Unit Tests
        run: npm run test:unit
